cookie:
  expiry_days: 7
  key: client_ledger_signature_key_ubah_ini
  name: client_ledger_auth_cookie
credentials:
  usernames:
    admin:
      email: admin@contoh.com
      failed_login_attempts: 0
      logged_in: false
      name: Administrator
      password: $2b$12$2H6iLq4hrBJT2xbj/dfmH./3ZKrpDQhgeDcS49I9iBsWBiDZ7brn6
pre-authorized:
  emails: []
